/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeportesActividadesRouteImport } from './routes/deportes-actividades'
import { Route as EmpleosRouteImport } from './routes/empleos'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as EscuelasRouteImport } from './routes/escuelas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HorarioCampanasRouteImport } from './routes/horario-campanas'
import { Route as LincolnRouteImport } from './routes/lincoln'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as ProgramasEstudiantesRouteImport } from './routes/programas-estudiantes'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActividadesRouteImport } from './routes/admin.actividades'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as AdminAparienciaRouteImport } from './routes/admin.apariencia'
import { Route as AdminArticulosRouteImport } from './routes/admin.articulos'
import { Route as AdminAyudaFamiliasRouteImport } from './routes/admin.ayuda-familias'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminContactosRouteImport } from './routes/admin.contactos'
import { Route as AdminDeportesActividadesRouteImport } from './routes/admin.deportes-actividades'
import { Route as AdminEmergentesRouteImport } from './routes/admin.emergentes'
import { Route as AdminEscuelasRouteImport } from './routes/admin.escuelas'
import { Route as AdminFuentesRouteImport } from './routes/admin.fuentes'
import { Route as AdminProgramasRouteImport } from './routes/admin.programas'
import { Route as AdminProgramasEstudiantesRouteImport } from './routes/admin.programas-estudiantes'
import { Route as AdminSolicitudesRouteImport } from './routes/admin.solicitudes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminVerificacionRouteImport } from './routes/admin.verificacion'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminRegistroRouteImport } from './routes/admin_.registro'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as EquiposIndexRouteImport } from './routes/equipos.index'
import { Route as EquiposSlugRouteImport } from './routes/equipos.$slug'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as TransporteDartRouteImport } from './routes/transporte.dart'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AdminDartIndexRouteImport } from './routes/admin.dart.index'
import { Route as AdminDartConfiguracionRouteImport } from './routes/admin.dart.configuracion'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesActividadesRoute = DeportesActividadesRouteImport.update({
  id: '/deportes-actividades',
  path: '/deportes-actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleosRoute = EmpleosRouteImport.update({
  id: '/empleos',
  path: '/empleos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscuelasRoute = EscuelasRouteImport.update({
  id: '/escuelas',
  path: '/escuelas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HorarioCampanasRoute = HorarioCampanasRouteImport.update({
  id: '/horario-campanas',
  path: '/horario-campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const LincolnRoute = LincolnRouteImport.update({
  id: '/lincoln',
  path: '/lincoln',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasEstudiantesRoute = ProgramasEstudiantesRouteImport.update({
  id: '/programas-estudiantes',
  path: '/programas-estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActividadesRoute = AdminActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAparienciaRoute = AdminAparienciaRouteImport.update({
  id: '/apariencia',
  path: '/apariencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticulosRoute = AdminArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyudaFamiliasRoute = AdminAyudaFamiliasRouteImport.update({
  id: '/ayuda-familias',
  path: '/ayuda-familias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactosRoute = AdminContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeportesActividadesRoute =
  AdminDeportesActividadesRouteImport.update({
    id: '/deportes-actividades',
    path: '/deportes-actividades',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEmergentesRoute = AdminEmergentesRouteImport.update({
  id: '/emergentes',
  path: '/emergentes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscuelasRoute = AdminEscuelasRouteImport.update({
  id: '/escuelas',
  path: '/escuelas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuentesRoute = AdminFuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramasRoute = AdminProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramasEstudiantesRoute =
  AdminProgramasEstudiantesRouteImport.update({
    id: '/programas-estudiantes',
    path: '/programas-estudiantes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSolicitudesRoute = AdminSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificacionRoute = AdminVerificacionRouteImport.update({
  id: '/verificacion',
  path: '/verificacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistroRoute = AdminRegistroRouteImport.update({
  id: '/admin_/registro',
  path: '/admin/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquiposRoute,
} as any)
const EquiposSlugRoute = EquiposSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquiposRoute,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TransporteDartRoute = TransporteDartRouteImport.update({
  id: '/transporte/dart',
  path: '/transporte/dart',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDartIndexRoute = AdminDartIndexRouteImport.update({
  id: '/dart/',
  path: '/dart/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDartConfiguracionRoute = AdminDartConfiguracionRouteImport.update({
  id: '/dart/configuracion',
  path: '/dart/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contact': typeof ContactRoute
  '/deportes-actividades': typeof DeportesActividadesRoute
  '/empleos': typeof EmpleosRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/escuelas': typeof EscuelasRoute
  '/faq': typeof FaqRoute
  '/horario-campanas': typeof HorarioCampanasRoute
  '/lincoln': typeof LincolnRoute
  '/mcp': typeof McpRoute
  '/programas': typeof ProgramasRoute
  '/programas-estudiantes': typeof ProgramasEstudiantesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/apariencia': typeof AdminAparienciaRoute
  '/admin/articulos': typeof AdminArticulosRoute
  '/admin/ayuda-familias': typeof AdminAyudaFamiliasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/deportes-actividades': typeof AdminDeportesActividadesRoute
  '/admin/emergentes': typeof AdminEmergentesRoute
  '/admin/escuelas': typeof AdminEscuelasRoute
  '/admin/fuentes': typeof AdminFuentesRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/admin/programas-estudiantes': typeof AdminProgramasEstudiantesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificacion': typeof AdminVerificacionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registro': typeof AdminRegistroRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/equipos/$slug': typeof EquiposSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/transporte/dart': typeof TransporteDartRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/dart/configuracion': typeof AdminDartConfiguracionRoute
  '/admin/dart/': typeof AdminDartIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/announcements': typeof AnnouncementsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contact': typeof ContactRoute
  '/deportes-actividades': typeof DeportesActividadesRoute
  '/empleos': typeof EmpleosRoute
  '/escuelas': typeof EscuelasRoute
  '/faq': typeof FaqRoute
  '/horario-campanas': typeof HorarioCampanasRoute
  '/lincoln': typeof LincolnRoute
  '/mcp': typeof McpRoute
  '/programas': typeof ProgramasRoute
  '/programas-estudiantes': typeof ProgramasEstudiantesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/apariencia': typeof AdminAparienciaRoute
  '/admin/articulos': typeof AdminArticulosRoute
  '/admin/ayuda-familias': typeof AdminAyudaFamiliasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/deportes-actividades': typeof AdminDeportesActividadesRoute
  '/admin/emergentes': typeof AdminEmergentesRoute
  '/admin/escuelas': typeof AdminEscuelasRoute
  '/admin/fuentes': typeof AdminFuentesRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/admin/programas-estudiantes': typeof AdminProgramasEstudiantesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificacion': typeof AdminVerificacionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registro': typeof AdminRegistroRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/equipos/$slug': typeof EquiposSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/transporte/dart': typeof TransporteDartRoute
  '/admin': typeof AdminIndexRoute
  '/equipos': typeof EquiposIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/dart/configuracion': typeof AdminDartConfiguracionRoute
  '/admin/dart': typeof AdminDartIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contact': typeof ContactRoute
  '/deportes-actividades': typeof DeportesActividadesRoute
  '/empleos': typeof EmpleosRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/escuelas': typeof EscuelasRoute
  '/faq': typeof FaqRoute
  '/horario-campanas': typeof HorarioCampanasRoute
  '/lincoln': typeof LincolnRoute
  '/mcp': typeof McpRoute
  '/programas': typeof ProgramasRoute
  '/programas-estudiantes': typeof ProgramasEstudiantesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actividades': typeof AdminActividadesRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/apariencia': typeof AdminAparienciaRoute
  '/admin/articulos': typeof AdminArticulosRoute
  '/admin/ayuda-familias': typeof AdminAyudaFamiliasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/deportes-actividades': typeof AdminDeportesActividadesRoute
  '/admin/emergentes': typeof AdminEmergentesRoute
  '/admin/escuelas': typeof AdminEscuelasRoute
  '/admin/fuentes': typeof AdminFuentesRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/admin/programas-estudiantes': typeof AdminProgramasEstudiantesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificacion': typeof AdminVerificacionRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/registro': typeof AdminRegistroRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/equipos/$slug': typeof EquiposSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/transporte/dart': typeof TransporteDartRoute
  '/admin/': typeof AdminIndexRoute
  '/equipos/': typeof EquiposIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/dart/configuracion': typeof AdminDartConfiguracionRoute
  '/admin/dart/': typeof AdminDartIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/admin'
    | '/announcements'
    | '/apps'
    | '/auth'
    | '/calendario'
    | '/contact'
    | '/deportes-actividades'
    | '/empleos'
    | '/equipos'
    | '/escuelas'
    | '/faq'
    | '/horario-campanas'
    | '/lincoln'
    | '/mcp'
    | '/programas'
    | '/programas-estudiantes'
    | '/search'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actividades'
    | '/admin/anuncios'
    | '/admin/apariencia'
    | '/admin/articulos'
    | '/admin/ayuda-familias'
    | '/admin/calendario'
    | '/admin/categorias'
    | '/admin/contactos'
    | '/admin/deportes-actividades'
    | '/admin/emergentes'
    | '/admin/escuelas'
    | '/admin/fuentes'
    | '/admin/programas'
    | '/admin/programas-estudiantes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/admin/verificacion'
    | '/admin/login'
    | '/admin/registro'
    | '/articles/$slug'
    | '/equipos/$slug'
    | '/guias/$slug'
    | '/topics/$slug'
    | '/transporte/dart'
    | '/admin/'
    | '/equipos/'
    | '/topics/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/dart/configuracion'
    | '/admin/dart/'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/announcements'
    | '/apps'
    | '/auth'
    | '/calendario'
    | '/contact'
    | '/deportes-actividades'
    | '/empleos'
    | '/escuelas'
    | '/faq'
    | '/horario-campanas'
    | '/lincoln'
    | '/mcp'
    | '/programas'
    | '/programas-estudiantes'
    | '/search'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actividades'
    | '/admin/anuncios'
    | '/admin/apariencia'
    | '/admin/articulos'
    | '/admin/ayuda-familias'
    | '/admin/calendario'
    | '/admin/categorias'
    | '/admin/contactos'
    | '/admin/deportes-actividades'
    | '/admin/emergentes'
    | '/admin/escuelas'
    | '/admin/fuentes'
    | '/admin/programas'
    | '/admin/programas-estudiantes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/admin/verificacion'
    | '/admin/login'
    | '/admin/registro'
    | '/articles/$slug'
    | '/equipos/$slug'
    | '/guias/$slug'
    | '/topics/$slug'
    | '/transporte/dart'
    | '/admin'
    | '/equipos'
    | '/topics'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/dart/configuracion'
    | '/admin/dart'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/admin'
    | '/announcements'
    | '/apps'
    | '/auth'
    | '/calendario'
    | '/contact'
    | '/deportes-actividades'
    | '/empleos'
    | '/equipos'
    | '/escuelas'
    | '/faq'
    | '/horario-campanas'
    | '/lincoln'
    | '/mcp'
    | '/programas'
    | '/programas-estudiantes'
    | '/search'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actividades'
    | '/admin/anuncios'
    | '/admin/apariencia'
    | '/admin/articulos'
    | '/admin/ayuda-familias'
    | '/admin/calendario'
    | '/admin/categorias'
    | '/admin/contactos'
    | '/admin/deportes-actividades'
    | '/admin/emergentes'
    | '/admin/escuelas'
    | '/admin/fuentes'
    | '/admin/programas'
    | '/admin/programas-estudiantes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/admin/verificacion'
    | '/admin_/login'
    | '/admin_/registro'
    | '/articles/$slug'
    | '/equipos/$slug'
    | '/guias/$slug'
    | '/topics/$slug'
    | '/transporte/dart'
    | '/admin/'
    | '/equipos/'
    | '/topics/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/dart/configuracion'
    | '/admin/dart/'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ContactRoute: typeof ContactRoute
  DeportesActividadesRoute: typeof DeportesActividadesRoute
  EmpleosRoute: typeof EmpleosRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  EscuelasRoute: typeof EscuelasRoute
  FaqRoute: typeof FaqRoute
  HorarioCampanasRoute: typeof HorarioCampanasRoute
  LincolnRoute: typeof LincolnRoute
  McpRoute: typeof McpRoute
  ProgramasRoute: typeof ProgramasRoute
  ProgramasEstudiantesRoute: typeof ProgramasEstudiantesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegistroRoute: typeof AdminRegistroRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  TransporteDartRoute: typeof TransporteDartRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes-actividades': {
      id: '/deportes-actividades'
      path: '/deportes-actividades'
      fullPath: '/deportes-actividades'
      preLoaderRoute: typeof DeportesActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleos': {
      id: '/empleos'
      path: '/empleos'
      fullPath: '/empleos'
      preLoaderRoute: typeof EmpleosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escuelas': {
      id: '/escuelas'
      path: '/escuelas'
      fullPath: '/escuelas'
      preLoaderRoute: typeof EscuelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horario-campanas': {
      id: '/horario-campanas'
      path: '/horario-campanas'
      fullPath: '/horario-campanas'
      preLoaderRoute: typeof HorarioCampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lincoln': {
      id: '/lincoln'
      path: '/lincoln'
      fullPath: '/lincoln'
      preLoaderRoute: typeof LincolnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas-estudiantes': {
      id: '/programas-estudiantes'
      path: '/programas-estudiantes'
      fullPath: '/programas-estudiantes'
      preLoaderRoute: typeof ProgramasEstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actividades': {
      id: '/admin/actividades'
      path: '/actividades'
      fullPath: '/admin/actividades'
      preLoaderRoute: typeof AdminActividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apariencia': {
      id: '/admin/apariencia'
      path: '/apariencia'
      fullPath: '/admin/apariencia'
      preLoaderRoute: typeof AdminAparienciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articulos': {
      id: '/admin/articulos'
      path: '/articulos'
      fullPath: '/admin/articulos'
      preLoaderRoute: typeof AdminArticulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayuda-familias': {
      id: '/admin/ayuda-familias'
      path: '/ayuda-familias'
      fullPath: '/admin/ayuda-familias'
      preLoaderRoute: typeof AdminAyudaFamiliasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contactos': {
      id: '/admin/contactos'
      path: '/contactos'
      fullPath: '/admin/contactos'
      preLoaderRoute: typeof AdminContactosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deportes-actividades': {
      id: '/admin/deportes-actividades'
      path: '/deportes-actividades'
      fullPath: '/admin/deportes-actividades'
      preLoaderRoute: typeof AdminDeportesActividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergentes': {
      id: '/admin/emergentes'
      path: '/emergentes'
      fullPath: '/admin/emergentes'
      preLoaderRoute: typeof AdminEmergentesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escuelas': {
      id: '/admin/escuelas'
      path: '/escuelas'
      fullPath: '/admin/escuelas'
      preLoaderRoute: typeof AdminEscuelasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fuentes': {
      id: '/admin/fuentes'
      path: '/fuentes'
      fullPath: '/admin/fuentes'
      preLoaderRoute: typeof AdminFuentesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programas': {
      id: '/admin/programas'
      path: '/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AdminProgramasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programas-estudiantes': {
      id: '/admin/programas-estudiantes'
      path: '/programas-estudiantes'
      fullPath: '/admin/programas-estudiantes'
      preLoaderRoute: typeof AdminProgramasEstudiantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitudes': {
      id: '/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AdminSolicitudesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion': {
      id: '/admin/verificacion'
      path: '/verificacion'
      fullPath: '/admin/verificacion'
      preLoaderRoute: typeof AdminVerificacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/registro': {
      id: '/admin_/registro'
      path: '/admin/registro'
      fullPath: '/admin/registro'
      preLoaderRoute: typeof AdminRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof EquiposRoute
    }
    '/equipos/$slug': {
      id: '/equipos/$slug'
      path: '/$slug'
      fullPath: '/equipos/$slug'
      preLoaderRoute: typeof EquiposSlugRouteImport
      parentRoute: typeof EquiposRoute
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporte/dart': {
      id: '/transporte/dart'
      path: '/transporte/dart'
      fullPath: '/transporte/dart'
      preLoaderRoute: typeof TransporteDartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dart/': {
      id: '/admin/dart/'
      path: '/dart'
      fullPath: '/admin/dart/'
      preLoaderRoute: typeof AdminDartIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dart/configuracion': {
      id: '/admin/dart/configuracion'
      path: '/dart/configuracion'
      fullPath: '/admin/dart/configuracion'
      preLoaderRoute: typeof AdminDartConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActividadesRoute: typeof AdminActividadesRoute
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminAparienciaRoute: typeof AdminAparienciaRoute
  AdminArticulosRoute: typeof AdminArticulosRoute
  AdminAyudaFamiliasRoute: typeof AdminAyudaFamiliasRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminContactosRoute: typeof AdminContactosRoute
  AdminDeportesActividadesRoute: typeof AdminDeportesActividadesRoute
  AdminEmergentesRoute: typeof AdminEmergentesRoute
  AdminEscuelasRoute: typeof AdminEscuelasRoute
  AdminFuentesRoute: typeof AdminFuentesRoute
  AdminProgramasRoute: typeof AdminProgramasRoute
  AdminProgramasEstudiantesRoute: typeof AdminProgramasEstudiantesRoute
  AdminSolicitudesRoute: typeof AdminSolicitudesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVerificacionRoute: typeof AdminVerificacionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDartConfiguracionRoute: typeof AdminDartConfiguracionRoute
  AdminDartIndexRoute: typeof AdminDartIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActividadesRoute: AdminActividadesRoute,
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminAparienciaRoute: AdminAparienciaRoute,
  AdminArticulosRoute: AdminArticulosRoute,
  AdminAyudaFamiliasRoute: AdminAyudaFamiliasRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminContactosRoute: AdminContactosRoute,
  AdminDeportesActividadesRoute: AdminDeportesActividadesRoute,
  AdminEmergentesRoute: AdminEmergentesRoute,
  AdminEscuelasRoute: AdminEscuelasRoute,
  AdminFuentesRoute: AdminFuentesRoute,
  AdminProgramasRoute: AdminProgramasRoute,
  AdminProgramasEstudiantesRoute: AdminProgramasEstudiantesRoute,
  AdminSolicitudesRoute: AdminSolicitudesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVerificacionRoute: AdminVerificacionRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDartConfiguracionRoute: AdminDartConfiguracionRoute,
  AdminDartIndexRoute: AdminDartIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EquiposRouteChildren {
  EquiposSlugRoute: typeof EquiposSlugRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposSlugRoute: EquiposSlugRoute,
  EquiposIndexRoute: EquiposIndexRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ContactRoute: ContactRoute,
  DeportesActividadesRoute: DeportesActividadesRoute,
  EmpleosRoute: EmpleosRoute,
  EquiposRoute: EquiposRouteWithChildren,
  EscuelasRoute: EscuelasRoute,
  FaqRoute: FaqRoute,
  HorarioCampanasRoute: HorarioCampanasRoute,
  LincolnRoute: LincolnRoute,
  McpRoute: McpRoute,
  ProgramasRoute: ProgramasRoute,
  ProgramasEstudiantesRoute: ProgramasEstudiantesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegistroRoute: AdminRegistroRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  TransporteDartRoute: TransporteDartRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
